"""Rendering helpers for LLM and deterministic fallback narratives."""

from __future__ import annotations

from typing import Any

from credit_risk_altdata.llm.constants import (
    DRAFT_DISCLAIMER,
    REPORT_TYPE_ADVERSE_ACTION,
    REPORT_TYPE_PLAIN,
    REPORT_TYPE_UNDERWRITER,
    ReportType,
)


def normalize_generated_text(text: str) -> str:
    """Normalize generated text for stable artifact output."""
    stripped_lines = [line.strip() for line in text.splitlines()]
    non_empty = [line for line in stripped_lines if line]
    return "\n".join(non_empty).strip()


def _feature_names(rows: list[dict[str, Any]], *, limit: int) -> list[str]:
    names: list[str] = []
    for row in rows:
        feature_name_raw = row.get("feature_name")
        if isinstance(feature_name_raw, str) and feature_name_raw.strip():
            names.append(feature_name_raw.strip())
        if len(names) >= limit:
            break
    return names


def _format_feature_list(names: list[str]) -> str:
    if not names:
        return "no strong feature-level evidence was available"
    if len(names) == 1:
        return names[0]
    return ", ".join(names[:-1]) + f", and {names[-1]}"


def render_fallback_report(
    *,
    report_type: ReportType,
    applicant_id: int | str,
    explanation_method_source: str,
    cohort_name: str | None,
    predicted_probability: float,
    threshold: float,
    predicted_label: int | None,
    actual_label: int | None,
    top_risk_increasing_features: list[dict[str, Any]],
    top_risk_decreasing_features: list[dict[str, Any]],
    source_explanation_generated: bool,
    source_failure_reason: str | None,
    generation_failure_reason: str | None,
    disclaimer: str = DRAFT_DISCLAIMER,
) -> str:
    """Deterministic fallback narrative when local LLM generation is unavailable."""
    increasing = _format_feature_list(_feature_names(top_risk_increasing_features, limit=3))
    decreasing = _format_feature_list(_feature_names(top_risk_decreasing_features, limit=3))

    fallback_reason = generation_failure_reason or "local LLM unavailable"
    source_reason = source_failure_reason or "none"
    cohort_value = cohort_name if cohort_name is not None else "unknown"

    if report_type == REPORT_TYPE_PLAIN:
        lines = [
            (
                f"Applicant {applicant_id} has predicted default probability "
                f"{predicted_probability:.3f} compared with threshold {threshold:.3f}."
            ),
            (
                "The main risk-increasing factors in the structured explanation were "
                f"{increasing}."
            ),
            (
                "Risk-mitigating factors included "
                f"{decreasing}."
            ),
            (
                "This narrative was generated by deterministic fallback mode because "
                f"{fallback_reason}."
            ),
            disclaimer,
        ]
        return " ".join(lines)

    if report_type == REPORT_TYPE_UNDERWRITER:
        lines = [
            f"- Applicant ID: {applicant_id}",
            (
                "- Score context: "
                f"predicted_probability={predicted_probability:.3f}, "
                f"threshold={threshold:.3f}"
            ),
            f"- Primary risk-increasing factors: {increasing}",
            f"- Primary risk-decreasing factors: {decreasing}",
            f"- Cohort/method: cohort={cohort_value}, method={explanation_method_source}",
            (
                "- Generation mode: deterministic fallback "
                f"(reason={fallback_reason}; "
                f"source_explanation_generated={source_explanation_generated}; "
                f"source_failure_reason={source_reason})"
            ),
            f"- Disclaimer: {disclaimer}",
        ]
        return "\n".join(lines)

    if report_type == REPORT_TYPE_ADVERSE_ACTION:
        lines = [
            (
                "Draft explanatory statement: based on the current model output, this case "
                f"was evaluated with predicted_probability={predicted_probability:.3f} against "
                f"threshold={threshold:.3f}."
            ),
            (
                "Principal factors associated with elevated modeled risk were "
                f"{increasing}."
            ),
            (
                "Factors associated with lower modeled risk included "
                f"{decreasing}."
            ),
            (
                "This text was produced using deterministic fallback mode because "
                f"{fallback_reason}."
            ),
            (
                f"Context: predicted_label={predicted_label}, actual_label={actual_label}, "
                f"cohort={cohort_value}, method={explanation_method_source}."
            ),
            disclaimer,
        ]
        return " ".join(lines)

    raise ValueError(f"Unsupported report type: {report_type}")
